services:
  - type: web
    name: node-whatsapp
    runtime: node
    buildCommand: npm install && cd vue && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
